// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://brmayccvnjfshsnaqtim.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJybWF5Y2N2bmpmc2hzbmFxdGltIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc1MDg4MjksImV4cCI6MjA3MzA4NDgyOX0.g6R4V2bHRHcH1IkkMPbyg8HO5tSkTBABFNTBrND8mmo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});